### ISSUE TITLE
getFormat fatal error

### ISSUE THREAD

**Issue by elwingert** [wingmingchan/php7-cascade-ws-ns#4]
When attempting to retrieve a format with via soap and the following call:
$f = a\Format::getFormat( $service, $id );
I receive the following error:
Fatal error: Uncaught Error: Using $this when not in object context in php7-cascade-ws-ns/cascade_ws_ns7/asset_classes/Format.class.php:129

Is this local to my instance of cascade server or an issue with the library in general or maybe I should be doing this in a different manner now?  This code did work as expected in the past (previous version of cascade server and previous version of your library) but I am now experiencing the error above.

**Comment by wingmingchan** [comment]
$(USorry for the bugs. They were introduced early this year when I added the REST code. Now they have been fixed. Please replace the Format class https://github.com/wingmingchan/php7-cascade-ws-ns/blob/master/cascade_ws_ns7/asset_classes/Format.class.php and your code should work now. 

Wing

>>> Eric <notifications@github.com> 10/9/2018 5:58 PM >>>

When attempting to retrieve a format with via soap and the following call:
$f = a\Format::getFormat( $service, $id );
I receive the following error:
Fatal error: Uncaught Error: Using $this when not in object context in php7-cascade-ws-ns/cascade_ws_ns7/asset_classes/Format.class.php:129 
Is this local to my instance of cascade server or an issue with the library in general or maybe I should be doing this in a different manner now? This code did work as expected in the past (previous version of cascade server and previous version of your library) but I am now experiencing the error above.

**Comment by elwingert** [comment]
Success!  thank you!
